import type { Program } from "@/components/ProgramCard";


export const courses: Program[] = [
    {
        title: "Foundation Skill Development Program",
        description:
            "A structured foundation program designed to take learners from zero technical knowledge to real-world development, automation testing, and API fundamentals using industry tools and hands-on practice.",
        level: "Beginner",
        duration: "4 Months",
        mode: "Live Classes (Online)",
        classesPerWeek: "4 classes/week",
        certificate: true,
        originalPrice: 9999,
        price: 4999,
        curriculum: [
            "Development Environment Setup: VS Code & Linux Basics",
            "Web Development Fundamentals: HTML, CSS & JavaScript",
            "Version Control & Collaboration using Git and GitHub",
            "Live Project Deployment using Netlify / Vercel",
            "Python Programming with Core Concepts & OOPs",
            "Logical Problem Solving using Python",
            "Automation Testing Basics with Selenium (UI Testing)",
            "API Fundamentals & API Testing using Postman",
            "Certificate from Skellify (ISO 9001:2015 certified organization)",
        ],
        enrollUrl: "https://forms.gle/8Si6GePwSBYGepg27",
    },
    {
        title: "Python Programming with OOPs (Core Concepts & Logic)",
        description:
            "A beginner-friendly Python course focused on programming fundamentals, core data structures, and object-oriented thinking to build strong logic and clean coding practices.",
        level: "Beginner",
        duration: "3 Months",
        mode: "Live Classes (Online)",
        classesPerWeek: "3 classes/week",
        certificate: true,
        originalPrice: 5999,
        price: 2999,
        curriculum: [
            "Introduction to Programming & Python Environment Setup",
            "Python Basics: Syntax, Variables & Data Types",
            "Control Flow: Conditions, Loops & Logical Thinking",
            "Functions & Modular Programming Concepts",
            "Core Data Structures: List, Tuple, Set & Dictionary",
            "Object-Oriented Programming: Classes & Objects",
            "OOPs Principles: Inheritance, Polymorphism & Encapsulation",
            "Exception Handling, Debugging & File Handling Basics",
            "Certificate from Skellify (ISO 9001:2015 certified organization)",
        ],
        enrollUrl: "https://forms.gle/cBhjDimrHXCBXNa8A",
    },
    {
        title: "Java Programming with OOPs (Core Concepts & Logic)",
        description:
            "A Java course focused on building strong programming fundamentals, object-oriented design, and logical problem-solving for backend and enterprise-level development paths.",
        level: "Beginner",
        duration: "3 Months",
        mode: "Live Classes (Online)",
        classesPerWeek: "3 classes/week",
        certificate: true,
        originalPrice: 5999,
        price: 2999,
        curriculum: [
            "Introduction to Java & Development Environment Setup",
            "Java Basics: Syntax, Variables & Data Types",
            "Control Flow: Conditional Statements & Loops",
            "Methods & Modular Programming in Java",
            "Object-Oriented Programming: Classes & Objects",
            "OOPs Principles: Inheritance, Polymorphism & Encapsulation",
            "Arrays & Introduction to Java Collections",
            "Exception Handling & Basic Debugging Concepts",
            "Certificate from Skellify (ISO 9001:2015 certified organization)",
        ],
    },
];


export const internships: Program[] = [
    {
        title: "Web Development OJT Program (Live Project Based)",
        description:
            "An industry-oriented OJT program where participants contribute to real-world web applications, work with APIs, and collaborate using professional development workflows.",
        level: "Intermediate",
        duration: "1 Month OJT",
        mode: "Online",
        classesPerWeek: "4 classes/week",
        certificate: true,
        originalPrice: 4999,
        price: 2499,
        featured: true,
        curriculum: [
            "Frontend Architecture & Component Design",
            "API & Backend Integration",
            "GitHub Collaboration & Version Control",
            "Live Project Development",
            "Certificate from Skellify (ISO 9001:2015 certified organization)",
        ],
        projects: ["E-commerce platform", "Real-time dashboard application"],
        outcomes: [
            "Build full-stack web apps",
            "Deploy to production",
            "Implement authentication and APIs",
        ],
        enrollUrl: "https://forms.gle/9ooHGVh9RstUfMFw8",
    },
    {
        title: "Automation Testing OJT Program (Industry Practice)",
        description:
            "A hands-on On-the-Job Training program focused on real-world automation testing practices. Participants work on live websites, build automation frameworks, and follow industry-level QA workflows.",
        level: "Intermediate",
        duration: "1 Month OJT",
        mode: "Online",
        classesPerWeek: "3 classes/week",
        certificate: true,
        originalPrice: 4999,
        price: 2499,
        curriculum: [
            "Live Website Automation Testing",
            "Automation Framework Development",
            "Bug Reporting & Defect Tracking Process",
            "Real-world Project Implementation",
            "Certificate from Skellify (ISO 9001:2015 certified organization)",
        ],
        projects: ["End-to-end test suite for web app", "CI/CD automation pipeline"],
        outcomes: [
            "Build automation test frameworks",
            "Integrate tests in CI/CD",
            "Write comprehensive test strategies",
        ],
        enrollUrl: "https://forms.gle/9uTdGVwKN8V4dyZT8",
    },
    {
        title: "App Development OJT Program (Mobile Application)",
        description:
            "A practical OJT program focused on building and debugging mobile applications, covering UI implementation, API integration, and application lifecycle understanding.",
        level: "Intermediate",
        duration: "1 Month OJT",
        mode: "Online",
        classesPerWeek: "3 classes/week",
        certificate: true,
        originalPrice: 4999,
        price: 2499,
        curriculum: [
            "Mobile UI/UX Implementation",
            "State Management & Application Flow",
            "API Integration & Data Handling",
            "Real-world App Project Development",
            "Certificate from Skellify (ISO 9001:2015 certified organization)",
        ],
        projects: ["Team-led SaaS product build", "Open-source contribution sprint"],
        outcomes: [
            "Work in agile teams",
            "Deliver production features",
            "Navigate real codebase complexity",
        ],
        enrollUrl: "https://forms.gle/gd5A8DnEkJXEwYYu7",
    },
];